version: '2'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  go:
    build:
      dockerfile: dev/Dockerfile
      context: .
    image: jancajthaml/rest-contract-test-base
    volumes:
      - ./dev/lifecycle:/opt/lifecycle
      - .:/go/src/github.com/jancajthaml/rest-contract-test
    working_dir: /go/src/github.com/jancajthaml/rest-contract-test
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
      - COMPOSE_PROJECT_NAME
    entrypoint: ["go"]
    privileged: true

  # -------------------------------------------------------------------------- #

  service:
    build:
      dockerfile: Dockerfile
      context: .
    image: jancajthaml/rest-contract-test
    restart: "no"

  # -------------------------------------------------------------------------- #

  sync:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure"]

  # -------------------------------------------------------------------------- #

  init:
    extends: go
    entrypoint: ["dep"]
    command: ["init"]

  # -------------------------------------------------------------------------- #

  update:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure", "-update"]

  # -------------------------------------------------------------------------- #

  fetch:
    extends: go
    entrypoint: ["dep"]
    command: ["ensure", "-add", "github.com/advance512/yaml"]

  # -------------------------------------------------------------------------- #

  lint:
    extends: go
    entrypoint: ["/opt/lifecycle/lint"]

  # -------------------------------------------------------------------------- #

  package:
    extends: go
    entrypoint: ["/opt/lifecycle/package"]

  # -------------------------------------------------------------------------- #

  testee:
    hostname: testee
    build:
      dockerfile: Dockerfile
      context: bbtest
    image: jancajthaml/rest-contract-test-bbtest
    ports:
      - "8080:8080/tcp"

  # -------------------------------------------------------------------------- #

  test:
    extends: go
    command: ["test", "-v", "./...", "-timeout=20s"]

  # -------------------------------------------------------------------------- #

  bench:
    extends: go
    environment:
      - GOMAXPROCS=1
    command: ["test", "-v", "./...", "-benchmem", "-bench=.", "-timeout=20s"]

# ---------------------------------------------------------------------------- #

volumes:
  journal:
    driver: local
  metrics:
    driver: local

# ---------------------------------------------------------------------------- #
