required = [
  "github.com/sirupsen/logrus"
]

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/tsaikd/go-raml-parser"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
