required = [
  "github.com/sirupsen/logrus"
]

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "v0"
  name = "gopkg.in/raml.v0"

[[constraint]]
  branch = "master"
  name = "github.com/tsaikd/go-raml-parser"
